version: '3'
services:
  moodle:
    image: moodlehq/moodle-php-apache:8.3
    ports:
      - "${MOODLE_FORWARDED_PORT:-8100}:80"
    volumes:
      - ./vendor/moodle/moodle:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./config.php:/var/www/html/config.php
      - ./custom_plugins/blocks/helloblock:/var/www/html/blocks/helloblock
      - moodle_data:/var/www/moodledata
    environment:
      PHP_INI-upload_max_filesize: "200M"
      PHP_INI-post_max_size: "210M"
    env_file: .env

  db:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"

  mailpit:
    image: 'axllent/mailpit:latest'
    restart: unless-stopped
    ports:
      - '${MAIL_FORWARDED_PORT:-1025}:1025'
      - '${MAIL_FORWARDED_DASHBOARD_PORT:-8025}:8025'
    volumes:
      - mailpit_data:/data
    environment:
      MP_DATA_FILE: /data/mailpit.db

volumes:
  mailpit_data:
  moodle_data:
  postgres_data:
